baseURL = "https://jmw.sh/"
languageCode = "en-us"
title = "Jacob Woliver"
theme="archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# summarylength doesn't work right: https://discourse.gohugo.io/t/hugo-summarylength-doesnt-work/20881
# summarylength = 20

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle="[make lame things so I can eventually make great things](paulgraham.com/early.html)"
    homeDisplay=2

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jmwoliver"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jacobwoliver/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/jmwoliver/"

# Main menu Items

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 1

[[menu.main]]
name = "Writings"
url = "/writings"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4
