[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.22.0"

[[redirects]]
  from = "/index.xml"
  to = "/rss.xml"
  status = 301

[[redirects]]
  from = "/writings"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/writings/:slug"
  to = "/blog/:slug/"
  status = 301

[[redirects]]
  from = "/google-advertising-and-kagi"
  to = "/blog/google-advertising-and-kagi/"
  status = 301

[[redirects]]
  from = "/hui"
  to = "/blog/hui/"
  status = 301

[[redirects]]
  from = "/jacob-on-the-shortness-of-life"
  to = "/blog/jacob-on-the-shortness-of-life/"
  status = 301

[[redirects]]
  from = "/understanding-history-and-trade-offs"
  to = "/blog/understanding-history-and-trade-offs/"
  status = 301

[[redirects]]
  from = "/guiding-principles"
  to = "/blog/guiding-principles/"
  status = 301

[[redirects]]
  from = "/playing-with-generics-in-go"
  to = "/blog/playing-with-generics-in-go/"
  status = 301

[[redirects]]
  from = "/upload-multiple-files-with-go"
  to = "/blog/upload-multiple-files-with-go/"
  status = 301

[[redirects]]
  from = "/optimize-for-the-common-case"
  to = "/blog/optimize-for-the-common-case/"
  status = 301

[[redirects]]
  from = "/enjoy-the-process"
  to = "/blog/enjoy-the-process/"
  status = 301

[[redirects]]
  from = "/eulers-method-and-approximating-the-future"
  to = "/blog/eulers-method-and-approximating-the-future/"
  status = 301

[[redirects]]
  from = "/vgdownloader"
  to = "/blog/vgdownloader/"
  status = 301

[[redirects]]
  from = "/stackoverflow_prettifier"
  to = "/blog/stackoverflow_prettifier/"
  status = 301

[[redirects]]
  from = "/funny"
  to = "/"
  status = 301
